@Restaurants.API_HostAddress = http://localhost:61941
@token = CfDJ8KJXnzV7ultOlnImQiJxTk8lLhZjh07XBZtOCeoGENqRxVP2zQRlTWKYhj4on2Ne_l72KmPtniUccT2Vu0ms6rCEmFgZG4uMs_ZoT-SrGmNFogdfWMU8-UOrzZujEuDBCKtG_6c7GSsTUZD4MMEKPOVVHwvSyvFqmZ5_5Rv7xKL3UbRcL62HP4P1nIH7m6-TZReUvEWjV157yNO0b69NrSsgLatguqFs0Rn3cS8OCulTdF-c99ihoAk_JKNfaUb5yJYRQnRmkb0WAne5ADOIGC7RrNZSqjyoUB4S2XP9-o1Q4iu2j_8V6H9tPe4o69KkxOcgzMWkPqcR1WC0M4yUA5vYP39I4jvQdXGf1CTFdnjAoDz0TSEyFAhzdtpwfpGh7enlH8YnBV4mtALWF1S-fGrxxipLjJh6m-qz0OxS5Jq_nOr3vZLWMJw9-2grw2ZQYEQN-uuiy1OavKjLsDYzI5v_nwA0C4yqZdLHrmbIAuVzCwduk-sNk5_vH5DJs2t0H4ZhUj_a_xHbXy9pOxKnJ6wqM8TGHmCrOKEpYrkNZdFRh8A2WultX0kjw_Fq8fvHXZ5JmScgWhZpsqzgUEZN07NaXuIzVwy01gZgdh3CQ97-ezqJa-mp78VhHdDUFxCC1KV9a01Uwp0E_XFWdgovBv7m-XNdXlX8RWhzaIIb9SCD0Y3qhPLOWTdmrbnukk2_-kqB0BpMzqnQ_G_kFNbAox1U9mQidNyssZml9ZO1XAEZwAmTATOBOIzTgWlci1Vql0so2Y9AlOJil8encS_ob96TRjA_Lr7QYI1AcywQH2utsW2UkfS1wY4o_cJjL4Lws8KWwOrRHdVKdGsrFp72Yuc3kB6ir71Mw7M5XAAGNvcFVIWpO2NV2kZOhOsexaoIig

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

@id=4
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Authorization : Bearer {{token}}
###


POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization : Bearer {{token}}
Content-Type: application/json

{
  
   "Name": "PBbb9",
  "Description": "pbbb (short for Kentucky Fried Chicken) is an American fast food restaurant chain headquartered in Louisville, Kentucky, that specializes in fried chicken.",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "conta9@PBbb.com",
  "ContactNumber": "215478988",
  "City": "London",
  "Street": "Cork St 5",
  "PostalCode": "848213"
}

###



###
@id=4
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{id}
Content-Type: application/json

{
  
}

###

@restaurantId = 4
POST {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json

{
  "Name": "KFC4",
  "Description": "Hot Chicken",
  "Price": 8,
  "KiloCalories": 9
  
}

###

@restaurantId = 2
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/7/dishes/1

###

@restaurantId =2
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###



POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "Owner@gmail.com",
  
  "password": "User@12345"

}


