@Restaurants.API_HostAddress = http://localhost:61941
@token = CfDJ8KJXnzV7ultOlnImQiJxTk9zHTX5JeskeRj7J40Q_-gevAgTDvT-IXD6g3W19Bmz_PASz16n9lwzzEeiGYVug4h6JjHpOECC1oUFDi5CaRzsKvHvwSTQqv2QtZ7ia4ro-ufacpstOlMz2YQYvIYuDDSHRFjZxKOPRO5TDM7cdYCc8C3zVnte0EPxB4ahLRWPACZxwPlHlUt5xW2gp7YJu1n7jdUl0UigNthXRhd6-jyaKzH9bLgsGrjbW5VqlCPV1e5e345GcHZ9UVmbU33gTWmlVJY4GNOEsCWiwuE6L8MoYFG7JmKIaQXEQKpCYhqicro6bOhvHI8mw95snIrfKSeJz8MzEPGt5F5G7SO7L6_mgIEKqEG9WSTZmSx_o0WD538NTWM01YLAf6Macq_nbb_IQZihOIXstJCYFYP0yXI-90LPAagIvTYFTsmlNL43OWS2Q_LdsiiS-xEWLJz1oG6MHgcimehrxt0Lcp2RGQs-vUPQUwIRdkhULd4UM7blRX0kIaoXrCeNwt4_DzASmfs8hyhq1_Z0XnDzlsJXDg_2MI1kMICCJsAg8zQ1OqNsIuILC2HuUySI5moaJ_cFRgpoQPm84C2EZpAopW5ztA6n3n4G7AfvhWGOTmyr8Q7Qyt9qQlN4oNj4_HWoYqueGMF5bDuYYUJgyyhP9uzVRu1WcFZEo8x8zIi6BvQe-u1xqXc36LlzOgNcWctpWc9Tb2aM5h6v58GGZUt3KolYtHSGFfUzTvywTn-ns1kQCfK2CDuVMKGj7eYuiVzuRi4OtbvLTohWrNvTyZt8ygBsn6Xu

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

@id=4
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Authorization : Bearer {{token}}
###


POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization : Bearer {{token}}
Content-Type: application/json

{
  
   "Name": "PBbb8",
  "Description": "pbbb (short for Kentucky Fried Chicken) is an American fast food restaurant chain headquartered in Louisville, Kentucky, that specializes in fried chicken.",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "contac@PBbb.com",
  "ContactNumber": "215478988",
  "City": "London",
  "Street": "Cork St 5",
  "PostalCode": "848213"
}

###



###
@id=4
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{id}
Content-Type: application/json

{
  
}

###

@restaurantId = 4
POST {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json

{
  "Name": "KFC4",
  "Description": "Hot Chicken",
  "Price": 8,
  "KiloCalories": 9
  
}

###

@restaurantId = 2
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/7/dishes/1

###

@restaurantId =2
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###



POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "cceraju1@gmail.com",
  
  "password": "User@12345"

}
# "password": "User@12345"


