@Restaurants.API_HostAddress = http://localhost:61941
@token = CfDJ8KJXnzV7ultOlnImQiJxTk-9ezG9L8AmNT1JWN5SfxPw40vhLaW1bdfhy9z3NsIKF6-jsCXoD-51Eyc6iEPN781i-r5S4V1VP8goTLYQff4SsLK3BiWLU1AXmTY3Ka1WgtRNdHGgHyLXC9QA1I5CtweyJ1KC6tu_QPUww5yjp1JSwCZbygVdM8ilff_GdrlUd1LY9CKujdJR-VCnVi3m0leFN2rSSfexHsWetvKB6x0nCIrSwRSYzOwjqiEp6GSsierStUp1zwxiv550k8sNMRNUYyxL0kKpu85Vs-pmBanFRxfTJFe0aowzH0lDIxYwjIUUzMXeKIh_Zap3k3ULxbYtW45qs9KXhqvpnsExnLQ17A15-WReFfPhRgbw6IcZGpyNO_4AnP5RvvhAy1bAILcUCRgowXWDRIqb5Vk0vuWryJmoeSv51oZto33vpPsToON_rVyV9S0Uih5DinZt93MAkeQMDwZ-XisuKhZUHVt1sSEWBebFL_eU6YYY3F3Ov2C728ejnViChNX_K_cdPRgwHCORo8VUbeehzafzShCQvaZ9te0GM-_6rQvfrZBr4uKbcXUTfejuNbVFjBkrNs3LA4FdFYWWqTKNMOdyIx6FiPsMhXMbvXma1jR_dUJn0aJrec0eQkpiayKWzUJ5USjfQvia7nKpvapkq5TYGnVwjOnn7bACZWPuBfC2ANLzFg0ttg8FkOAaRqrwUXpNNg7k6vTPR6tUBwylN92fpJLfJK2gEHAAPVPZ5kfIE6WWa2yt0KelC9Ce7PYpvPiCWbV1U3P12gPf_FQqjrn7mw8P

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

@id=4
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Authorization : Bearer {{token}}
###


POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization : Bearer {{token}}
Content-Type: application/json

{
  
   "Name": "Owner22",
  "Description": "Owner policy check pbbb (short for Kentucky Fried Chicken) is an American fast food restaurant chain headquartered in Louisville, Kentucky, that specializes in fried chicken.",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "conta11@PBbb.com",
  "ContactNumber": "215478988",
  "City": "London",
  "Street": "Cork St 5",
  "PostalCode": "848213"
}

###



###
@id=4
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{id}
Content-Type: application/json

{
  
}

###

@restaurantId = 4
POST {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json

{
  "Name": "KFC4",
  "Description": "Hot Chicken",
  "Price": 8,
  "KiloCalories": 9
  
}

###

@restaurantId = 2
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/7/dishes/1

###

@restaurantId =2
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###



POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "Owner2@gmail.com",
  "password": "User@12345"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{$bearerToken}}
Content-Type: application/json

{
  //AssignUserRoleCommand
}

###
